---
- hosts: all
  roles:
    - role: '{{playbook_dir}}'
      java_oracle_prefix: jdk
      java_oracle_cleanup: True
  tasks:
    - name: confirm java is executable
      command: /usr/local/java/bin/java -version
      
