---
# defaults file for java-oracle

# jre or jdk
java_oracle_prefix: jre

java_oracle_ver : 8
java_oracle_minor_ver : 0
java_oracle_patch_ver: 131
java_oracle_post_patch_ver: b11

java_oracle_uuid: d54c1d3a095b4ff2b6607d096fa80163
java_oracle_platform: linux-x64
java_oracle_mirror: http://download.oracle.com/otn-pub/java/jdk

java_oracle_parent_install_dir: /usr/local

java_oracle_cleanup: False
